build:
  # You can add any tests to this section
  image: python:2
  commands:
    - echo "Building..."

publish:
  # This section will publish a docker image with a tag matching the git branch
  docker:
    repo: $$DOCKER_USERNAME/$$DOCKER_REPO
    tag: "$${BRANCH##feature/}"
    username: $$DOCKER_USERNAME
    password: $$DOCKER_PASSWORD
    email: $$DOCKER_EMAIL

  # This section will publish a docker image tagged "latest" if the branch is master
  docker:
    repo: $$DOCKER_USERNAME/$$DOCKER_REPO
    tag: "latest"
    username: $$DOCKER_USERNAME
    password: $$DOCKER_PASSWORD
    email: $$DOCKER_EMAIL
    when:
      branch: "master"

deploy:
  webhook:
    image: plugins/drone-webhook
    skip_verify: true
    method: POST
    auth:
      username: $$MANTL_USERNAME
      password: $$MANTL_PASSWORD
    urls:
      - https://$$MANTL_CONTROL/marathon/v2/apps/$$DEPLOYMENT_DIR/$$BOT_NAME/$$DOCKER_USERNAME/restart?force=true
    when:
      branch: "master"

notify:
  # This section will send build notifications via Cisco Spark.
  spark:
    image: hpreston/drone-spark
    roomId: $$SPARK_ROOM
    auth_token: $$SPARK_TOKEN
