build:
  # You can add any tests to this section
  image: python:2
  commands:
    - echo "Building..."

publish:
  docker:
    repo: $$DOCKER_USERNAME/$$DOCKER_REPO
    tag: "latest"
    username: $$DOCKER_USERNAME
    password: $$DOCKER_PASSWORD
    email: $$DOCKER_EMAIL

deploy:
  webhook:
    image: plugins/drone-webhook
    skip_verify: true
    method: POST
    auth:
      username: $$MANTL_USERNAME
      password: $$MANTL_PASSWORD
    urls:
      - https://$$MANTL_CONTROL/marathon/v2/apps/$$PROD_APP_NAME/restart?force=true
    when:
      branch: "master"

deploy:
  webhook:
    image: plugins/drone-webhook
    skip_verify: true
    method: POST
    auth:
      username: $$MANTL_USERNAME
      password: $$MANTL_PASSWORD
    urls:
      - https://$$MANTL_CONTROL/marathon/v2/apps/$$TEST_APP_NAME/restart?force=true
    when:
      branch: "test"

notify:
  # This section will send build notifications via Cisco Spark.
  spark:
    image: hpreston/drone-spark
    roomId: $$SPARK_ROOM
    auth_token: $$SPARK_TOKEN
